package com.spring.dev.home.AuthApp.model;

public enum City {
	ARIANA , SFAX , BEJA , BENAROUS , BIZERTE ,GABES ,GAFSA ,JENDOUBA , KAIROUAN , KASSERINE , KEBILI , KEF ,MAHDIA , MANNOUBA , MEDNINE ,MONASTIR , NABEUL , BOUZID , SILIANA , SOUSSE , TATAOUIN ,TOUZER , ZAGHOUAN , TUNIS
}
